Repository cadet/CADET-Verification, pull requests merged in 2024-11, with the labels that each got.

#18 Separate chromatography sensitivity tests
  src/test_cadet_core/bench_configs.py
  src/test_cadet_core/chromatography.py
  src/test_cadet_core/verify_cadet-core.py
Labels: enhancement

#20 Update environment
  environment.yml
  src/test_cadet_core/utility/convergence.py
Labels: enhancement

#21 Update environment
  environment.yml
Labels: bug

#23 Set CADET-Python to version 0.14.1
  environment.yml
  src/test_cadet_core/bench_func.py
Labels: maintenance

#25 Fix SyntaxWarning: invalid escape sequence
  src/test_cadet_core/bench_func.py
  src/test_cadet_core/utility/convergence.py
Labels: maintenance

#30 Add output remote info to .cadet-rdm-data.json
  .cadet-rdm-data.json
Labels: meta
